Added reasonPhraseExtended()
j-ulrich/http-status-codes-cpp pull request #2
Opened 2018-10-03 13:44 UTC by jjberry314

Added reasonPhraseExtended() to allow retrieval of extended human-readable description text
Added some missing codes

2018-10-04 21:03 UTC, j-ulrich requested changes
@jjberry314
Thank you for your contribution! I appreciate that!

Please let me know if you don't want to take care of my review comments, then I will do it.

2018-10-04 21:03 UTC, j-ulrich commented on HttpStatusCodes_C++11.h
> +	case 306: return "Switch Proxy";
That code is not registered with the IANA (see https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml) and it is also not defined above. So it should be removed here again.

2018-10-04 21:03 UTC, j-ulrich commented on HttpStatusCodes_C++.h
> +	LoopDetected                  = 508, //!< The server detected an infinite loop while processing the request (sent in lieu of 208 Already Reported). [WebDAV; RFC 5842]
If you add `508 LoopDetected`, you should also add `208 Already Reported` from the [same RFC](https://tools.ietf.org/html/rfc5842#section-7.1).

2018-10-04 21:03 UTC, j-ulrich commented on HttpStatusCodes_C++.h
> +	UseProxy          = 305, //!< The requested resource is available only through a proxy, the address for which is provided in the response. Many HTTP clients (such as Mozilla and Internet Explorer) d
IMO, the `\deprecated` should be kept since [RFC 7231](https://tools.ietf.org/html/rfc7231#section-6.4.5) explicitly states that it is deprecated.
However, we can keep the description in addition:
```
//!< \deprecated \parblock Due to security concerns regarding in-band configuration of a proxy. \endparblock
//!< The requested resource MUST be accessed through the proxy given by the Location field.
```
The `\parblock \endparblock` prevents that the description is put into the "Deprecated" block.

2018-10-04 21:03 UTC, j-ulrich commented on HttpStatusCodes_C++.h
> +	EarlyHints         = 103, //!< Used to return some response headers before final HTTP message.
The description should be taken from the RFC:
```
//!< Indicates to the client that the server is likely to send a final response with the header fields included in the informational response.
```

2018-10-04 21:03 UTC, j-ulrich commented on HttpStatusCodes_C++.h
> +	LoopDetected                  = 508, //!< The server detected an infinite loop while processing the request (sent in lieu of 208 Already Reported). [WebDAV; RFC 5842]
Again, use the description from the RFC:
```
//!< Indicates that the server terminated an operation because it encountered an infinite loop while processing a request with "Depth: infinity". [RFC 5842]
```

2018-10-04 21:03 UTC, j-ulrich commented on HttpStatusCodes_C++.h
> +	NotExtended                   = 510, //!< Further extensions to the request are required for the server to fulfill it. [RFC 2774]
Description from RFC:
```
//!<   The policy for accessing the resource has not been met in the request. [RFC 2774]
```

2018-10-04 21:03 UTC, j-ulrich commented on HttpStatusCodes_C++.h
> +	case 306: return "Switch Proxy";
See comment below

2018-10-04 21:03 UTC, j-ulrich commented on HttpStatusCodes_C++.h
> +inline std::string reasonPhraseExtended(int code)
Where do you have the description texts from?
They don't match the comments (descriptions from RFCs) from above (at least, not all of them).
So the question is whether the texts can be put into public domain (CC0).

2018-10-04 21:03 UTC, j-ulrich commented on HttpStatusCodes_C++.h
> +inline std::string reasonPhraseExtended(int code)
What's the use case for those descriptions?
I'm a bit reluctant to adding such description texts as code into the library since they are not universally usable. An application might want different texts or it might need the texts to be translatable.

In any case, the name of the method is misleading. It should rather be `description(int code)`

2018-10-04 21:53 UTC, jjberry314 commented on HttpStatusCodes_C++11.h
> +	case 306: return "Switch Proxy";
I'm happy to defer to the IANA on this!

2018-10-04 21:53 UTC, jjberry314 commented on HttpStatusCodes_C++.h
> +	LoopDetected                  = 508, //!< The server detected an infinite loop while processing the request (sent in lieu of 208 Already Reported). [WebDAV; RFC 5842]
Good point. The RFC has authority here.

2018-10-04 21:53 UTC, jjberry314 commented on HttpStatusCodes_C++.h
> +	UseProxy          = 305, //!< The requested resource is available only through a proxy, the address for which is provided in the response. Many HTTP clients (such as Mozilla and Internet Explorer) d
Agreed. Fair point.

2018-10-04 21:54 UTC, jjberry314 commented on HttpStatusCodes_C++.h
> +	EarlyHints         = 103, //!< Used to return some response headers before final HTTP message.
Yes, agreed. The RFC has authority

2018-10-04 21:54 UTC, jjberry314 commented on HttpStatusCodes_C++.h
> +	NotExtended                   = 510, //!< Further extensions to the request are required for the server to fulfill it. [RFC 2774]
Agreed. RFC has authority

2018-10-04 21:57 UTC, jjberry314 commented on HttpStatusCodes_C++.h
> +inline std::string reasonPhraseExtended(int code)
I confess the description texts come from Wikipedia. I agree that they should come from the RFCs instead. 

As for the description text, now that I have started using it in code I realise that they aren't actually very useful and don't add a lot. I intended them to give more description in error longs. But I think that code + phrase is probably sufficient, especially if formatted as code + ": " + phrase. If the user wants more information, they can always look it up on Wikipedia. :)
So maybe, on reflection, this is not needed at all. Which was really my main contribution and now I think is wasted effort. ha ha. Oh well.

2018-10-04 21:58 UTC, jjberry314 commented on HttpStatusCodes_C++.h
> +	case 306: return "Switch Proxy";
Indeed

2018-10-04 22:15 UTC, jjberry314 commented
I think, on reflection, my changes can be discarded if you wish. I don't think I need reasonPhraseExtended() at all now. If my other tweaks are useful then please feel free to adopt them, or just reject the pull request.

2018-10-05 10:43 UTC, jjberry314 commented
I've replaced reasonPhraseExtended() and replaced it with reasonPhraseEx() which emits "HTTP <code>: phrase" where a phrase is available or "HTTP <code>" if not. 

I have not addressed your other review comments at this time. I have no strong feeling about keeping those changes, as I don't really need them. I'm happy to revert them.

2018-10-06 20:09 UTC, j-ulrich commented
> I've replaced reasonPhraseExtended() and replaced it with reasonPhraseEx() which emits "HTTP code: phrase" where a phrase is available or "HTTP code" if not.

Sorry, but IMO the format of that string is application specific and therefore does not belong into the library. Someone else might need such a message to be formatted like "HTTP \<code\> - \<phrase\>" or "\<phrase\> (\<code\>)" or whatever.

So I will now create a separate pull request to add the missing status codes but leave out the `reasonPhraseEx()` function.
Let me know if you see it differently.

2018-10-06 20:09 UTC, closed without merging

2018-10-07 14:43 UTC, jjberry314 commented
I completely understand and accept your reasoning. 

Thank you for being so patient with me.