added toInt function
j-ulrich/http-status-codes-cpp pull request #5
Opened 2018-11-16 19:27 UTC by fro0m

2018-11-23 22:20 UTC, j-ulrich reviewed
Thank you for your contribution! I appreciate that!

Let me know if you can and want to take care of the review comments. Else I will take care of them.

2018-11-23 22:20 UTC, j-ulrich commented on HttpStatusCodes_C++11.h
> +/*! Explicitly converts code to int
The parameter and return value should be formally documented:
```suggestion
/*! Converts a Code to its corresponding integer value.
 * \param code The code to be converted.
 * \return The numeric value of \p code.
```

2018-11-23 22:22 UTC, j-ulrich commented on HttpStatusCodes_C++11.h
> +int toInt(Code code)
The `toInt()` method should also get a unit test.

2018-11-23 22:26 UTC, j-ulrich requested changes
The added feature should be documented in the `CHANGELOG.md` like this:
```
---


## Unreleased ##

### Added ###
- [#5] toInt() method to convert HttpStatus::Code to integer in C++11 variant.


---
```

And in the `README.md` (replacing the "QNetworkReply::NetworkError Mapping" section):

    ### Conversion Functions ###
    
    #### C++11 Variant ####
    
    ```c++
    int HttpStatus::toInt(Code code);
    ```
    Returns the numerical value of a given `HttpStatus::Code`. This method is provided for convenience to avoid writing a `static_cast<int>()`.
    
    #### Qt Variant ####
    > **Note:** Available only if the Qt::Network module is available.
    ```c++
    int HttpStatus::networkErrorToStatusCode(QNetworkReply::NetworkError error);
    ```
    Returns the HTTP status code corresponding to the given _error_ if there is one.
    Otherwise, `-1` is returned.
    
    ```c++
    QNetworkReply::NetworkError HttpStatus::statusCodeToNetworkError(int code);
    ```
    Returns the `QNetworkReply::NetworkError` corresponding to the given _code_ if there is one.
    For codes where there is no exact match, the best matchnig "catch all" code (`QNetworkReply::NoError`,
    `QNetworkReply::UnknownContentError`, `QNetworkReply::UnknownServerError` or `QNetworkReply::ProtocolFailure`)
    is returned.
    ```

2018-12-09 15:00 UTC, fro0m commented
Please take care of unit-tests and better to make the function explicitly inline.

2019-01-06 13:05 UTC, j-ulrich commented
Closing this PR in favor of #6 which also takes care of the review comments.

Thanks @fro0m for the contribution!

2019-01-06 13:05 UTC, closed without merging